from datetime import date
from django.db import migrations

def poblar_videojuegos(apps, schema_editor):
    Videojuego = apps.get_model('app', 'Videojuego')

    Videojuego.objects.create(title='Alan Wake', release_date=date(2010, 5, 14), rating=0, image='alan-wake.jpg', genero='Horror')
    Videojuego.objects.create(title='Among Us', release_date=date(2018, 6, 15), rating=0, image='among-us.jpg', genero='Arcade')
    Videojuego.objects.create(title='Assassin’s Creed Odyssey', release_date=date(2018, 10, 5), rating=0, image='ac-odyssey.jpg', genero='RPG')
    Videojuego.objects.create(title='Assassin’s Creed Valhalla', release_date=date(2020, 11, 10), rating=0, image='ac-valhalla.jpg', genero='RPG')
    Videojuego.objects.create(title='Apex Legends', release_date=date(2019, 2, 4), rating=0, image='apex.jpg', genero='Shooter')
    Videojuego.objects.create(title='Atomic Heart', release_date=date(2023, 2, 21), rating=0, image='atomic-heart.jpg', genero='Shooter')
    Videojuego.objects.create(title='Back 4 Blood', release_date=date(2021, 10, 12), rating=0, image='back4blood.jpg', genero='Shooter')
    Videojuego.objects.create(title='Battlefield 1', release_date=date(2016, 10, 21), rating=0, image='battlefield1.jpg', genero='Shooter')
    Videojuego.objects.create(title='Battlefield 2042', release_date=date(2021, 11, 19), rating=0, image='battlefield2042.jpg', genero='Shooter')
    Videojuego.objects.create(title='Bayonetta 3', release_date=date(2022, 10, 28), rating=0, image='bayonetta3.jpg', genero='Arcade')
    Videojuego.objects.create(title='Bloodborne', release_date=date(2015, 3, 24), rating=0, image='bloodborne.jpg', genero='Horror')
    Videojuego.objects.create(title='Borderlands 3', release_date=date(2019, 9, 13), rating=0, image='borderlands3.jpg', genero='Shooter')
    Videojuego.objects.create(title='Call of Duty: Modern Warfare', release_date=date(2019, 10, 25), rating=0, image='cod-mw.jpg', genero='Shooter')
    Videojuego.objects.create(title='Call of Duty: Warzone', release_date=date(2020, 3, 10), rating=0, image='cod-warzone.jpg', genero='Shooter')
    Videojuego.objects.create(title='Cuphead', release_date=date(2017, 9, 29), rating=0, image='cuphead.jpg', genero='Arcade')
    Videojuego.objects.create(title='Cyberpunk 2077', release_date=date(2020, 12, 10), rating=0, image='cyberpunk.jpg', genero='RPG')
    Videojuego.objects.create(title='Dark Souls III', release_date=date(2016, 3, 24), rating=0, image='darksouls3.jpg', genero='RPG')
    Videojuego.objects.create(title='Days Gone', release_date=date(2019, 4, 26), rating=0, image='daysgone.jpg', genero='Horror')
    Videojuego.objects.create(title='Dead by Daylight', release_date=date(2016, 6, 14), rating=0, image='dbd.jpg', genero='Horror')
    Videojuego.objects.create(title='Dead Space Remake', release_date=date(2023, 1, 27), rating=0, image='deadspace-remake.jpg', genero='Horror')
    Videojuego.objects.create(title='Death Stranding', release_date=date(2019, 11, 8), rating=0, image='deathstranding.jpg', genero='RPG')
    Videojuego.objects.create(title='Demon’s Souls (Remake)', release_date=date(2020, 11, 12), rating=0, image='demonsouls-remake.jpg', genero='RPG')
    Videojuego.objects.create(title='Destiny 2', release_date=date(2017, 9, 6), rating=0, image='destiny2.jpg', genero='MMO')
    Videojuego.objects.create(title='Doom Eternal', release_date=date(2020, 3, 20), rating=0, image='doom-eternal.jpg', genero='Shooter')
    Videojuego.objects.create(title='Dragon Age: Inquisition', release_date=date(2014, 11, 18), rating=0, image='dragonage-inquisition.jpg', genero='RPG')
    Videojuego.objects.create(title='Dragon Ball FighterZ', release_date=date(2018, 1, 26), rating=0, image='dbfz.jpg', genero='Arcade')
    Videojuego.objects.create(title='Dying Light', release_date=date(2015, 1, 27), rating=0, image='dyinglight.jpg', genero='Horror')
    Videojuego.objects.create(title='Elden Ring', release_date=date(2022, 2, 25), rating=0, image='eldenring.jpg', genero='RPG')
    Videojuego.objects.create(title='Fall Guys', release_date=date(2020, 8, 4), rating=0, image='fallguys.jpg', genero='Arcade')
    Videojuego.objects.create(title='Fallout 4', release_date=date(2015, 11, 10), rating=0, image='fallout4.jpg', genero='RPG')
    Videojuego.objects.create(title='Far Cry 5', release_date=date(2018, 3, 27), rating=0, image='farcry5.jpg', genero='Shooter')
    Videojuego.objects.create(title='FIFA 23', release_date=date(2022, 9, 30), rating=0, image='fifa23.jpg', genero='Arcade')
    Videojuego.objects.create(title='Final Fantasy VII Remake', release_date=date(2020, 4, 10), rating=0, image='ff7-remake.jpg', genero='RPG')
    Videojuego.objects.create(title='Final Fantasy XVI', release_date=date(2023, 6, 22), rating=0, image='ff16.jpg', genero='RPG')
    Videojuego.objects.create(title='For Honor', release_date=date(2017, 2, 14), rating=0, image='forhonor.jpg', genero='MMO')
    Videojuego.objects.create(title='Fortnite', release_date=date(2017, 7, 25), rating=0, image='fortnite.jpg', genero='Shooter')
    Videojuego.objects.create(title='Gears 5', release_date=date(2019, 9, 10), rating=0, image='gears5.jpg', genero='Shooter')
    Videojuego.objects.create(title='Ghost of Tsushima', release_date=date(2020, 7, 17), rating=0, image='ghost-tsushima.jpg', genero='RPG')
    Videojuego.objects.create(title='Grand Theft Auto Vice City', release_date=date(2002, 10, 29), rating=0, image='gta-vc.jpg', genero='RPG')
    Videojuego.objects.create(title='Grand Theft Auto San Andreas', release_date=date(2004, 10, 26), rating=0, image='gta-sa.jpg', genero='RPG')
    Videojuego.objects.create(title='Grand Theft Auto IV', release_date=date(2008, 4, 29), rating=0, image='gta4.jpg', genero='RPG')
    Videojuego.objects.create(title='Grand Theft Auto V', release_date=date(2013, 9, 17), rating=0, image='gta6.jpg', genero='RPG')
    Videojuego.objects.create(title='God of War (2018)', release_date=date(2018, 4, 20), rating=0, image='gow-2018.jpg', genero='RPG')
    Videojuego.objects.create(title='God of War Ragnarök', release_date=date(2022, 11, 9), rating=0, image='gow-ragnarok.jpg', genero='RPG')
    Videojuego.objects.create(title='Gran Turismo 7', release_date=date(2022, 3, 4), rating=0, image='gt7.jpg', genero='Arcade')
    Videojuego.objects.create(title='Half-Life: Alyx', release_date=date(2020, 3, 23), rating=0, image='hl-alyx.jpg', genero='Shooter')
    Videojuego.objects.create(title='Hades', release_date=date(2020, 9, 17), rating=0, image='hades.jpg', genero='Arcade')
    Videojuego.objects.create(title='Halo Infinite', release_date=date(2021, 12, 8), rating=0, image='halo-infinite.jpg', genero='Shooter')
    Videojuego.objects.create(title='Hellblade: Senua’s Sacrifice', release_date=date(2017, 8, 8), rating=0, image='hellblade.jpg', genero='Horror')
    Videojuego.objects.create(title='Hollow Knight', release_date=date(2017, 2, 27), rating=0, image='hollow-knight.jpg', genero='Arcade')
    Videojuego.objects.create(title='Hogwarts Legacy', release_date=date(2023, 2, 10), rating=0, image='hogwarts.jpg', genero='RPG')
    Videojuego.objects.create(title='Horizon Forbidden West', release_date=date(2022, 2, 18), rating=0, image='horizon-fw.jpg', genero='RPG')
    Videojuego.objects.create(title='Inazuma Eleven', release_date=date(2008, 8, 22), rating=0, image='ie1.jpg', genero='Arcade')
    Videojuego.objects.create(title='Inazuma Eleven 2', release_date=date(2009, 10, 1), rating=0, image='ie2.jpg', genero='Arcade')
    Videojuego.objects.create(title='Inazuma Eleven 3', release_date=date(2010, 7, 1), rating=0, image='ie3.jpg', genero='Arcade')
    Videojuego.objects.create(title='It Takes Two', release_date=date(2021, 3, 26), rating=0, image='it-takes-two.jpg', genero='Arcade')
    Videojuego.objects.create(title='Left 4 Dead 2', release_date=date(2009, 11, 17), rating=0, image='l4d2.jpg', genero='Shooter')
    Videojuego.objects.create(title='League of Legends', release_date=date(2009, 10, 27), rating=0, image='lol.jpg', genero='MMO')
    Videojuego.objects.create(title='Little Nightmares II', release_date=date(2021, 2, 11), rating=0, image='little-nightmares-2.jpg', genero='Horror')
    Videojuego.objects.create(title='Mass Effect Legendary Edition', release_date=date(2021, 5, 14), rating=0, image='mass-effect-le.jpg', genero='RPG')
    Videojuego.objects.create(title='Metro Exodus', release_date=date(2019, 2, 15), rating=0, image='metro-exodus.jpg', genero='Shooter')
    Videojuego.objects.create(title='Minecraft', release_date=date(2011, 11, 18), rating=0, image='minecraft.jpg', genero='Arcade')
    Videojuego.objects.create(title='Monster Hunter: World', release_date=date(2018, 1, 26), rating=0, image='monster-hunter-world.jpg', genero='RPG')
    Videojuego.objects.create(title='Mortal Kombat 11', release_date=date(2019, 4, 23), rating=0, image='mk11.jpg', genero='Arcade')
    Videojuego.objects.create(title='NieR: Automata', release_date=date(2017, 2, 23), rating=0, image='nier-automata.jpg', genero='RPG')
    Videojuego.objects.create(title='No Man’s Sky', release_date=date(2016, 8, 9), rating=0, image='no-mans-sky.jpg', genero='MMO')
    Videojuego.objects.create(title='Outlast', release_date=date(2013, 9, 4), rating=0, image='outlast.jpg', genero='Horror')
    Videojuego.objects.create(title='Overwatch', release_date=date(2016, 5, 24), rating=0, image='overwatch.jpg', genero='Shooter')
    Videojuego.objects.create(title='Palworld', release_date=date(2024, 1, 19), rating=0, image='palworld.jpg', genero='MMO')
    Videojuego.objects.create(title='Path of Exile', release_date=date(2013, 10, 23), rating=0, image='path-of-exile.jpg', genero='MMO')
    Videojuego.objects.create(title='Persona 5 Royal', release_date=date(2019, 10, 31), rating=0, image='persona5r.jpg', genero='RPG')
    Videojuego.objects.create(title='Phasmophobia', release_date=date(2020, 9, 18), rating=0, image='phasmophobia.jpg', genero='Horror')
    Videojuego.objects.create(title='Pokemon Diamante Brillante', release_date=date(2021, 11, 19), rating=0, image='pkm-diamante.jpg', genero='RPG')
    Videojuego.objects.create(title='PUBG: Battlegrounds', release_date=date(2017, 3, 23), rating=0, image='pubg.jpg', genero='Shooter')
    Videojuego.objects.create(title='Rainbow Six Siege', release_date=date(2015, 12, 1), rating=0, image='r6siege.jpg', genero='Shooter')
    Videojuego.objects.create(title='Ratchet & Clank: Rift Apart', release_date=date(2021, 6, 11), rating=0, image='rnc-riftapart.jpg', genero='Arcade')
    Videojuego.objects.create(title='Red Dead Redemption 2', release_date=date(2018, 10, 26), rating=0, image='rdr2.jpg', genero='RPG')
    Videojuego.objects.create(title='Resident Evil 2 Remake', release_date=date(2019, 1, 25), rating=0, image='re2-remake.jpg', genero='Horror')
    Videojuego.objects.create(title='Resident Evil 4 Remake', release_date=date(2023, 3, 24), rating=0, image='re4-remake.jpg', genero='Horror')
    Videojuego.objects.create(title='Resident Evil Village', release_date=date(2021, 5, 7), rating=0, image='re-village.jpg', genero='Horror')
    Videojuego.objects.create(title='Returnal', release_date=date(2021, 4, 30), rating=0, image='returnal.jpg', genero='Horror')
    Videojuego.objects.create(title='Rocket League', release_date=date(2015, 7, 7), rating=0, image='rocketleague.jpg', genero='Arcade')
    Videojuego.objects.create(title='Sekiro: Shadows Die Twice', release_date=date(2019, 3, 22), rating=0, image='sekiro.jpg', genero='RPG')
    Videojuego.objects.create(title='Star Wars Jedi: Fallen Order', release_date=date(2019, 11, 15), rating=0, image='jedi-fallen.jpg', genero='RPG')
    Videojuego.objects.create(title='Starfield', release_date=date(2023, 9, 6), rating=0, image='starfield.jpg', genero='RPG')
    Videojuego.objects.create(title='Street Fighter 6', release_date=date(2023, 6, 2), rating=0, image='sf6.jpg', genero='Arcade')
    Videojuego.objects.create(title='Subnautica', release_date=date(2018, 1, 23), rating=0, image='subnautica.jpg', genero='Horror')
    Videojuego.objects.create(title='Super Mario Odyssey', release_date=date(2017, 10, 27), rating=0, image='mario-odyssey.jpg', genero='Arcade')
    Videojuego.objects.create(title='Super Smash Bros. Ultimate', release_date=date(2018, 12, 7), rating=0, image='ssbu.jpg', genero='Arcade')
    Videojuego.objects.create(title='Skylanders', release_date=date(2011, 10, 13), rating=0, image='skylanders.jpg', genero='Arcade')
    Videojuego.objects.create(title='Tales of Arise', release_date=date(2021, 9, 10), rating=0, image='tales-arise.jpg', genero='RPG')
    Videojuego.objects.create(title='The Callisto Protocol', release_date=date(2022, 12, 2), rating=0, image='callisto.jpg', genero='Horror')
    Videojuego.objects.create(title='The Last Of Us Part I', release_date=date(2013, 6, 14), rating=0, image='tlou1.jpg', genero='Arcade')
    Videojuego.objects.create(title='The Last Of Us Part II', release_date=date(2020, 6, 19), rating=0, image='tlou.jpg', genero='Arcade')
    Videojuego.objects.create(title='The Legend of Zelda: Breath of the Wild', release_date=date(2017, 3, 3), rating=0, image='zelda-botw.jpg', genero='RPG')
    Videojuego.objects.create(title='The Legend of Zelda: Tears of the Kingdom', release_date=date(2023, 5, 12), rating=0, image='zelda-totk.jpg', genero='RPG')
    Videojuego.objects.create(title='The Witcher 3: Wild Hunt', release_date=date(2015, 5, 19), rating=0, image='witcher3.jpg', genero='RPG')
    Videojuego.objects.create(title='Until Dawn', release_date=date(2015, 8, 25), rating=0, image='until-dawn.jpg', genero='Horror')
    Videojuego.objects.create(title='Valorant', release_date=date(2020, 6, 2), rating=0, image='valorant.jpg', genero='Shooter')
    Videojuego.objects.create(title='Warframe', release_date=date(2013, 3, 25), rating=0, image='warframe.jpg', genero='MMO')
    Videojuego.objects.create(title='World of Warcraft', release_date=date(2004, 11, 23), rating=0, image='wow.jpg', genero='MMO')

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(poblar_videojuegos),
    ]